# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations
import datetime
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustOrder',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('sep', models.CharField(default=b'\t', max_length=1)),
                ('queryLineNo', models.IntegerField(default=0)),
                ('queryName', models.URLField(default=b'')),
                ('type', models.CharField(default=b'', max_length=20)),
                ('purchaseDate', models.DateField(blank=True)),
                ('orderId', models.CharField(default=b'', max_length=50)),
                ('shipToName', models.CharField(default=b'', max_length=50)),
                ('shipToAddress1', models.CharField(default=b'', max_length=100)),
                ('shipToAddress2', models.CharField(default=b'', max_length=100)),
                ('shipToAddress3', models.CharField(default=b'', max_length=100)),
                ('shipToCity', models.CharField(default=b'', max_length=100)),
                ('shipToState', models.CharField(default=b'', max_length=100)),
                ('shipToZip', models.CharField(default=b'', max_length=100)),
                ('shipToCntry', models.CharField(default=b'', max_length=100)),
                ('packSlipType', models.CharField(default=b'', max_length=50)),
                ('carrier', models.CharField(default=b'', max_length=50)),
                ('orderType', models.CharField(default=b'', max_length=50)),
                ('serviceLevel', models.CharField(default=b'', max_length=50)),
                ('buyerEmail', models.EmailField(default=b'', max_length=254)),
                ('sku', models.CharField(default=b'', max_length=50)),
                ('productName', models.CharField(default=b'', max_length=100)),
                ('quantity', models.IntegerField(default=0)),
                ('parseError', models.TextField(default=b'')),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='CustOrderQueryRow',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('query', models.CharField(default=b'', max_length=1024)),
                ('queryId', models.DateTimeField(default=datetime.datetime(2014, 12, 30, 10, 32, 59, 511086, tzinfo=utc))),
                ('queryRecordNumber', models.IntegerField(default=0)),
                ('record', models.TextField(default=b'')),
                ('header', models.BooleanField(default=False)),
                ('parseError', models.TextField(default=b'')),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='PD',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('SEP', models.CharField(default=b'|', max_length=1)),
                ('REC_TYPE', models.CharField(default=b'PD', max_length=2)),
                ('PKT_SEQ_NBR', models.CharField(default=b'', max_length=9)),
                ('STAT_CODE', models.CharField(default=b'', max_length=2)),
                ('PKT_PROFILE_ID', models.CharField(default=b'', max_length=2, blank=True)),
                ('SEASON', models.CharField(default=b'', max_length=2, blank=True)),
                ('SEASON_YR', models.CharField(default=b'', max_length=2, blank=True)),
                ('STYLE', models.CharField(default=b'', max_length=8, blank=True)),
                ('STYLE_SFX', models.CharField(default=b'', max_length=8, blank=True)),
                ('COLOR', models.CharField(default=b'', max_length=4, blank=True)),
                ('COLOR_SFX', models.CharField(default=b'', max_length=2, blank=True)),
                ('SEC_DIM', models.CharField(default=b'', max_length=3, blank=True)),
                ('QUAL', models.CharField(default=b'', max_length=1, blank=True)),
                ('SIZE_RANGE_CODE', models.CharField(default=b'', max_length=4, blank=True)),
                ('SIZE_REL_POSN_IN_TABLE', models.CharField(default=b'', max_length=4, blank=True)),
                ('SIZE_DESC', models.CharField(default=b'', max_length=15, blank=True)),
                ('ORIG_ORD_QTY', models.CharField(default=b'', max_length=9, blank=True)),
                ('ORIG_PKT_QTY', models.CharField(default=b'', max_length=9, blank=True)),
                ('CANCEL_QTY', models.CharField(default=b'', max_length=9, blank=True)),
                ('CUBE_MULT_QTY', models.CharField(default=b'', max_length=9, blank=True)),
                ('BACK_ORD_QTY', models.CharField(default=b'', max_length=9, blank=True)),
                ('CUST_SKU', models.CharField(default=b'', max_length=20, blank=True)),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='PH',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('SEP', models.CharField(default=b'|', max_length=1)),
                ('itemIndex', models.IntegerField(default=0)),
                ('REC_TYPE', models.CharField(default=b'PH', max_length=2)),
                ('WHSE', models.CharField(default=b'', max_length=3)),
                ('CO', models.CharField(default=b'', max_length=10)),
                ('DIV', models.CharField(default=b'', max_length=10)),
                ('STAT_CODE', models.CharField(default=b'10', max_length=2)),
                ('PKT_PROFILE_ID', models.CharField(default=b'', max_length=10)),
                ('PKT_CTRL_NBR', models.CharField(default=b'', max_length=10)),
                ('PKT_NBR', models.CharField(default=b'', max_length=11, blank=True)),
                ('PKT_SFX', models.CharField(default=b'', max_length=3, blank=True)),
                ('ORD_NBR', models.CharField(default=b'', max_length=3, blank=True)),
                ('ORD_SFX', models.CharField(default=b'', max_length=3, blank=True)),
                ('ORD_TYPE', models.CharField(default=b'', max_length=2, blank=True)),
                ('SHIPTO', models.CharField(default=b'', max_length=10, blank=True)),
                ('SHIPTO_NAME', models.CharField(default=b'', max_length=35)),
                ('SHIPTO_CONTACT', models.CharField(default=b'', max_length=30)),
                ('SHIPTO_ADDR_1', models.CharField(default=b'', max_length=75, blank=True)),
                ('SHIPTO_ADDR_2', models.CharField(default=b'', max_length=75, blank=True)),
                ('SHIPTO_ADDR_3', models.CharField(default=b'', max_length=75, blank=True)),
                ('SHIPTO_CITY', models.CharField(default=b'', max_length=40, blank=True)),
                ('SHIPTO_STATE', models.CharField(default=b'', max_length=3, blank=True)),
                ('SHIPTO_ZIP', models.CharField(default=b'', max_length=11, blank=True)),
                ('SHIPTO_CNTRY', models.CharField(default=b'', max_length=4, blank=True)),
                ('TEL_NBR', models.CharField(default=b'', max_length=15, blank=True)),
                ('SOLDTO', models.CharField(default=b'', max_length=10, blank=True)),
                ('SOLDTO_NAME', models.CharField(default=b'', max_length=35, blank=True)),
                ('SOLDTO_ADDR_1', models.CharField(default=b'', max_length=75, blank=True)),
                ('SOLDTO_ADDR_2', models.CharField(default=b'', max_length=75, blank=True)),
                ('SOLDTO_ADDR_3', models.CharField(default=b'', max_length=75, blank=True)),
                ('SOLDTO_CITY', models.CharField(default=b'', max_length=40, blank=True)),
                ('SOLDTO_STATE', models.CharField(default=b'', max_length=3, blank=True)),
                ('SOLDTO_ZIP', models.CharField(default=b'', max_length=11, blank=True)),
                ('SOLDTO_CNTRY', models.CharField(default=b'', max_length=4, blank=True)),
                ('SHIP_VIA', models.CharField(default=b'UUS2', max_length=4, blank=True)),
                ('CARTON_LABEL_TYPE', models.CharField(default=b'', max_length=3, blank=True)),
                ('NBR_OF_LABEL', models.CharField(default=b'', max_length=3, blank=True)),
                ('CONTNT_LABEL_TYPE', models.CharField(default=b'', max_length=3, blank=True)),
                ('NBR_OF_CONTNT_LABEL', models.CharField(default=b'', max_length=3, blank=True)),
                ('NBR_OF_PAKING_SLIPS', models.CharField(default=b'', max_length=3, blank=True)),
                ('PACK_SLIP_TYPE', models.CharField(default=b'', max_length=2, blank=True)),
                ('LANG_ID', models.CharField(default=b'', max_length=3, blank=True)),
                ('PH1_REC_TYPE', models.CharField(default=b'PH1', max_length=3)),
                ('PH1_ACCT_RCVBL_ACCT_NBR', models.CharField(default=b'', max_length=10, blank=True)),
                ('PH1_ACCT_RCVBL_CODE', models.CharField(default=b'', max_length=2, blank=True)),
                ('PH1_CUST_PO_NBR', models.CharField(default=b'', max_length=26, blank=True)),
                ('PH1_PRTY_CODE', models.CharField(default=b'', max_length=2, blank=True)),
                ('PH1_PRTY_SFX', models.CharField(default=b'', max_length=3, blank=True)),
                ('PH1_ORD_DATE', models.CharField(default=b'', max_length=14, blank=True)),
                ('PH1_START_SHIP_DATE', models.CharField(default=b'', max_length=14, blank=True)),
                ('PH1_STOP_SHIP_DATE', models.CharField(default=b'', max_length=14, blank=True)),
                ('PH1_SCHED_DLVRY_DATE', models.CharField(default=b'', max_length=14, blank=True)),
                ('PH1_EARLIEST_DLVRY_TIME', models.CharField(default=b'', max_length=4, blank=True)),
                ('PH1_SCHED_DLVRY_DATE_END', models.CharField(default=b'', max_length=10, blank=True)),
                ('PH1_RTE_GUIDE_NBR', models.CharField(default=b'', max_length=10, blank=True)),
                ('PH1_CUST_RTE', models.CharField(default=b'', max_length=1, blank=True)),
                ('PH1_RTE_ATTR', models.CharField(default=b'', max_length=30, blank=True)),
                ('PH1_RTE_ID', models.CharField(default=b'', max_length=10, blank=True)),
                ('PH1_RTE_STOP_SEQ', models.CharField(default=b'', max_length=5, blank=True)),
                ('PH1_RTE_TO', models.CharField(default=b'', max_length=10, blank=True)),
                ('PH1_RTE_TYPE_1', models.CharField(default=b'', max_length=2, blank=True)),
                ('PH1_RTE_TYPE_2', models.CharField(default=b'', max_length=2, blank=True)),
                ('PH1_RTE_ZIP', models.CharField(default=b'', max_length=11, blank=True)),
                ('PH1_RTE_SWC_NBR', models.CharField(default=b'', max_length=10, blank=True)),
                ('PH1_CONSOL_NBR', models.CharField(default=b'', max_length=10, blank=True)),
                ('PH1_TOTAL_DLRS_UNDISC', models.CharField(default=b'', max_length=11, blank=True)),
                ('PH1_TOTAL_DLRS_DISC', models.CharField(default=b'', max_length=11, blank=True)),
                ('PH1_CURR_CODE', models.CharField(default=b'', max_length=10, blank=True)),
                ('PH1_PROD_VALUE', models.CharField(default=b'', max_length=11, blank=True)),
                ('PH1_FREIGHT_TERMS', models.CharField(default=b'', max_length=1, blank=True)),
                ('PH1_MARK_FOR', models.CharField(default=b'', max_length=25, blank=True)),
                ('PH1_INCO_TERMS', models.CharField(default=b'', max_length=3, blank=True)),
                ('PH1_BILL_ACCT_NBR', models.CharField(default=b'', max_length=10, blank=True)),
                ('PH1_COD_FUNDS', models.CharField(default=b'', max_length=1, blank=True)),
                ('PH1_INTL_GOODS_DESC', models.CharField(default=b'', max_length=35, blank=True)),
                ('PHI_REC_TYPEE', models.CharField(default=b'PHI', max_length=3)),
                ('PHI_SPL_INSTR_NBR', models.CharField(default=b'', max_length=3)),
                ('PHI_SPL_INSTR_TYPE', models.CharField(default=b'', max_length=2)),
                ('PHI_SPL_INSTR_CODE', models.CommaSeparatedIntegerField(default=b'08', max_length=2)),
                ('PHI_SPL_INSTR_DESC', models.CharField(default=b'', max_length=135)),
                ('PHI_PKT_PROFILE_ID', models.CharField(default=b'', max_length=10)),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='PickTicket',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('SEP', models.CharField(default=b'|', max_length=5)),
                ('HDR_REC_TYPE', models.CharField(default=b'HDR', max_length=3)),
                ('DOC_TYPE', models.CharField(default=b'PICKTICKET', max_length=10)),
                ('CMPY_NAME', models.CharField(default=b'', max_length=20)),
                ('DOC_DATE', models.CharField(default=b'12/30/14 10:32:59', max_length=17)),
                ('TRL_REC_TYPE', models.CharField(default=b'TRL', max_length=3)),
                ('parseErrors', models.TextField(default=b'')),
                ('fileName', models.URLField(default=b'')),
                ('fileContents', models.TextField(default=b'')),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='ShipmentOrderReport',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='ShipmentOrderRow',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.AddField(
            model_name='ph',
            name='ups_pkt',
            field=models.ForeignKey(to='ups.PickTicket'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='pd',
            name='ups_ph',
            field=models.ForeignKey(to='ups.PH'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='custorderqueryrow',
            name='ups_pkt',
            field=models.ForeignKey(to='ups.PickTicket'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='custorder',
            name='ups_pkt',
            field=models.ForeignKey(to='ups.PickTicket', blank=True),
            preserve_default=True,
        ),
    ]
