# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amazon_CO',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('fromFile', models.URLField(default=b'')),
                ('filename', models.URLField(default=b'')),
                ('type', models.CharField(default=b'Amazon', max_length=20)),
                ('buyer_name', models.CharField(default=b'', max_length=100)),
                ('buyer_email', models.EmailField(default=b'', max_length=254)),
                ('sku', models.CharField(default=b'', max_length=50)),
                ('product_name', models.CharField(default=b'', max_length=100)),
                ('purchase_date', models.DateField()),
                ('payments_date', models.DateField()),
                ('order_id', models.CharField(default=b'', max_length=50)),
                ('order_item_id', models.CharField(default=b'', max_length=50)),
                ('external_order_id', models.CharField(default=b'', max_length=50)),
                ('quantity_purchased', models.IntegerField(default=0)),
                ('currency', models.CharField(default=b'', max_length=50)),
                ('item_price', models.DecimalField(default=0, max_digits=6, decimal_places=2)),
                ('item_promotion_discount', models.DecimalField(default=0, max_digits=6, decimal_places=2)),
                ('item_promotion_id', models.CharField(default=b'', max_length=100)),
                ('ship_promotion_discount', models.DecimalField(default=0, max_digits=6, decimal_places=2)),
                ('ship_promotion_id', models.CharField(default=b'', max_length=100)),
                ('item_tax', models.DecimalField(default=0, max_digits=6, decimal_places=2)),
                ('shipping_price', models.DecimalField(default=0, max_digits=6, decimal_places=2)),
                ('shipping_tax', models.DecimalField(default=0, max_digits=6, decimal_places=2)),
                ('ship_service_level', models.CharField(default=b'', max_length=50)),
                ('recipient_name', models.CharField(default=b'', max_length=100)),
                ('ship_address_1', models.CharField(default=b'', max_length=200)),
                ('ship_address_2', models.CharField(default=b'', max_length=200)),
                ('ship_address_3', models.CharField(default=b'', max_length=200)),
                ('ship_city', models.CharField(default=b'', max_length=200)),
                ('ship_state', models.CharField(default=b'', max_length=20)),
                ('ship_postal_code', models.CharField(default=b'', max_length=20)),
                ('ship_country', models.CharField(default=b'', max_length=20)),
                ('ship_phone_number', models.CharField(default=b'', max_length=50)),
                ('delivery_start_date', models.DateField()),
                ('delivery_end_date', models.DateField()),
                ('delivery_time_zone', models.CharField(default=b'America/New_York', max_length=50)),
                ('delivery_Instructions', models.CharField(default=b'', max_length=500)),
                ('sales_channel', models.CharField(default=b'', max_length=50)),
                ('order_channel', models.CharField(default=b'', max_length=50)),
                ('order_channel_instance', models.CharField(default=b'', max_length=50)),
                ('tax_location_code', models.CharField(default=b'', max_length=200)),
                ('tax_location_city', models.CharField(default=b'', max_length=200)),
                ('tax_location_county', models.CharField(default=b'', max_length=50)),
                ('tax_location_state', models.CharField(default=b'', max_length=20)),
                ('per_unit_item_taxable_district', models.CharField(default=b'', max_length=200)),
                ('per_unit_item_taxable_city', models.CharField(default=b'', max_length=200)),
                ('per_unit_item_taxable_county', models.CharField(default=b'', max_length=200)),
                ('per_unit_item_taxable_state', models.CharField(default=b'', max_length=20)),
                ('per_unit_item_non_taxable_district', models.CharField(default=b'', max_length=200)),
                ('per_unit_item_non_taxable_city', models.CharField(default=b'', max_length=200)),
                ('per_unit_item_non_taxable_county', models.CharField(default=b'', max_length=200)),
                ('per_unit_item_non_taxable_state', models.CharField(default=b'', max_length=20)),
                ('per_unit_item_zero_rated_district', models.CharField(default=b'', max_length=200)),
                ('per_unit_item_zero_rated_city', models.CharField(default=b'', max_length=200)),
                ('per_unit_item_zero_rated_county', models.CharField(default=b'', max_length=200)),
                ('per_unit_item_zero_rated_state', models.CharField(default=b'', max_length=20)),
                ('per_unit_item_tax_collected_district', models.CharField(default=b'', max_length=200)),
                ('per_unit_item_tax_collected_city', models.CharField(default=b'', max_length=200)),
                ('per_unit_item_tax_collected_county', models.CharField(default=b'', max_length=200)),
                ('per_unit_item_tax_collected_state', models.CharField(default=b'', max_length=20)),
                ('per_unit_shipping_taxable_district', models.CharField(default=b'', max_length=200)),
                ('per_unit_shipping_taxable_city', models.CharField(default=b'', max_length=200)),
                ('per_unit_shipping_taxable_county', models.CharField(default=b'', max_length=200)),
                ('per_unit_shipping_taxable_state', models.CharField(default=b'', max_length=20)),
                ('per_unit_shipping_non_taxable_district', models.CharField(default=b'', max_length=200)),
                ('per_unit_shipping_non_taxable_city', models.CharField(default=b'', max_length=200)),
                ('per_unit_shipping_non_taxable_county', models.CharField(default=b'', max_length=200)),
                ('per_unit_shipping_non_taxable_state', models.CharField(default=b'', max_length=20)),
                ('per_unit_shipping_zero_rated_district', models.CharField(default=b'', max_length=200)),
                ('per_unit_shipping_zero_rated_city', models.CharField(default=b'', max_length=200)),
                ('per_unit_shipping_zero_rated_county', models.CharField(default=b'', max_length=200)),
                ('per_unit_shipping_zero_rated_state', models.CharField(default=b'', max_length=20)),
                ('per_unit_shipping_tax_collected_district', models.CharField(default=b'', max_length=200)),
                ('per_unit_shipping_tax_collected_county', models.CharField(default=b'', max_length=200)),
                ('per_unit_shipping_tax_collected_state', models.CharField(default=b'', max_length=200)),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='SS_CO',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('fromFile', models.URLField(default=b'')),
                ('filename', models.URLField(default=b'')),
                ('type', models.CharField(default=b'ShipStation', max_length=20)),
                ('sku', models.CharField(default=b'', max_length=50)),
                ('product_name', models.CharField(default=b'', max_length=100)),
                ('order_id', models.CharField(default=b'', max_length=50)),
                ('order_type', models.CharField(default=b'', max_length=50)),
                ('quantity_purchased', models.IntegerField(default=0)),
                ('purchase_date', models.DateField()),
                ('ship_service_level', models.CharField(default=b'', max_length=50)),
                ('recipient_name', models.CharField(default=b'', max_length=100)),
                ('buyer_email', models.EmailField(default=b'', max_length=254)),
                ('ship_address_1', models.CharField(default=b'', max_length=200)),
                ('ship_address_2', models.CharField(default=b'', max_length=200)),
                ('ship_address_3', models.CharField(default=b'', max_length=200)),
                ('ship_city', models.CharField(default=b'', max_length=100)),
                ('ship_state', models.CharField(default=b'', max_length=20)),
                ('ship_postal_code', models.CharField(default=b'', max_length=20)),
                ('ship_country', models.CharField(default=b'', max_length=50)),
                ('carrier', models.CharField(default=b'', max_length=20)),
                ('pack_slip_type', models.CharField(default=b'', max_length=20)),
                ('intl_terms_of_sale', models.CharField(default=b'', max_length=100)),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='UPS_CO_FILE',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('fileName', models.URLField(default=b'')),
                ('contents', models.TextField(default=b'')),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='UPS_PD',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='UPS_PH',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='UPS_PKT',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('SEP', models.CharField(default=b'|', max_length=5)),
                ('HDR_REC_TYPE', models.CharField(default=b'HDR', max_length=3)),
                ('DOC_TYPE', models.CharField(default=b'PICKTICKET', max_length=10)),
                ('CMPY_NAME', models.CharField(default=b'', max_length=20)),
                ('DOC_DATE', models.CharField(default=b'12/26/14 08:02:35', max_length=17)),
                ('TRL_REC_TYPE', models.CharField(default=b'TRL', max_length=3)),
                ('fileName', models.URLField(default=b'')),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='UPS_SO',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='UPS_SOR',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Zen_CO',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('fromFile', models.URLField(default=b'')),
                ('filename', models.URLField(default=b'')),
                ('type', models.CharField(default=b'Mirai', max_length=20)),
                ('v_date_purchased', models.DateField()),
                ('v_orders_status_name', models.CharField(default=b'', max_length=50)),
                ('v_orders_id', models.CharField(default=b'', max_length=50)),
                ('v_customers_id', models.CharField(default=b'', max_length=50)),
                ('v_customers_name', models.CharField(default=b'', max_length=100)),
                ('v_customers_company', models.CharField(default=b'', max_length=100)),
                ('v_customers_street_address', models.CharField(default=b'', max_length=200)),
                ('v_customers_suburb', models.CharField(default=b'', max_length=200)),
                ('v_customers_city', models.CharField(default=b'', max_length=100)),
                ('v_customers_postcode', models.CharField(default=b'', max_length=20)),
                ('v_customers_country', models.CharField(default=b'', max_length=200)),
                ('v_customers_telephone', models.CharField(default=b'', max_length=50)),
                ('v_customers_email_address', models.EmailField(max_length=254)),
                ('v_products_model', models.CharField(default=b'', max_length=100)),
                ('v_products_name', models.CharField(default=b'', max_length=100)),
                ('v_products_options', models.CharField(default=b'', max_length=100)),
                ('v_products_options_values', models.CharField(default=b'', max_length=200)),
                ('pkt', models.ForeignKey(to='ups.UPS_PKT', null=True)),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.AddField(
            model_name='ups_ph',
            name='pkt',
            field=models.ForeignKey(to='ups.UPS_PKT'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='ups_pd',
            name='ph',
            field=models.ForeignKey(to='ups.UPS_PH'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='ss_co',
            name='pkt',
            field=models.ForeignKey(to='ups.UPS_PKT', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='amazon_co',
            name='pkt',
            field=models.ForeignKey(to='ups.UPS_PKT', null=True),
            preserve_default=True,
        ),
    ]
